///////////////////////////////////////////////////////////////////////
// ExtensionAgentExample - Extension Agent Example Project for PGSuper
// Copyright © 1999-2017  Washington State Department of Transportation
//                        Bridge and Structures Office
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the Alternate Route Open Source License as 
// published by the Washington State Department of Transportation, 
// Bridge and Structures Office.
//
// This program is distributed in the hope that it will be useful, but 
// distribution is AS IS, WITHOUT ANY WARRANTY; without even the implied 
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See 
// the Alternate Route Open Source License for more details.
//
// You should have received a copy of the Alternate Route Open Source 
// License along with this program; if not, write to the Washington 
// State Department of Transportation, Bridge and Structures Office, 
// P.O. Box  47340, Olympia, WA 98503, USA or e-mail 
// Bridge_Support@wsdot.wa.gov
///////////////////////////////////////////////////////////////////////

// ExtensionAgentExample.idl : IDL source for ExtensionAgentExample
//

// This file will be processed by the MIDL tool to
// produce the type library (ExtensionAgentExample.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "WBFLCore.idl"; // for the Agent plugin

[
	uuid(4E7C50C2-59D4-4E54-892C-FB0428A54100),
	version(1.0),
	helpstring("SuperScriptingExtension Type Library")
]
library PGSuperScriptingExtensionLib
{
	importlib("stdole2.tlb");
	[
		uuid(9AD09682-03D8-42CF-B17A-6E679ABFD880),
		helpstring("PGSuperScriptingAgentClass")
	]
	coclass PGSuperScriptingAgent
	{
		[default] interface IAgentEx;
	};
};
